[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
InvertedFiles = "b20bd276-2c70-11ec-161a-3d1e1109a1c3"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Languages = "8ef0a80b-9436-5d2c-a485-80b904378c43"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SimSearchManifoldLearning = "ca7ab67e-1aa0-420a-90d9-eb5aef468722"
SimilaritySearch = "053f045d-5466-53fd-b400-a066f88fe02a"
Snowball = "fb8f903a-0164-4e73-9ffe-431110250c3b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TextSearch = "7f6f6c8a-3b03-11e9-223d-e7d88259bd6c"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
CategoricalArrays = "0.10.7"
Clustering = "0.14.4"
CodecZlib = "0.7.1"
DataFrames = "1.5.0"
Glob = "1.3.1"
HypertextLiteral = "0.9.4"
IJulia = "1.24.0"
InvertedFiles = "0.6.1"
JLD2 = "0.4.31"
JSON = "0.21.3"
Languages = "0.4.3"
Parquet2 = "0.2.11"
Query = "1.0.0"
Revise = "3.5.2"
SimSearchManifoldLearning = "0.2.8"
SimilaritySearch = "0.10.8"
Snowball = "0.1.0"
StatsBase = "0.33.21"
StatsPlots = "0.15.4"
TextSearch = "0.16.2"
UnPack = "1.0.2"
Statistics = "1.9.0"